import pandas as pd

df = pd.DataFrame([
    {
        "Order ID": "ORD00001",
        "Order Date": "2024-10-12",
        "Customer ID": "CUST3592",
        "Customer Name": "Customer 142",
        "Product ID / SKU": "SKU48471",
        "Product Name": "Vitamin C Serum",
        "Category": "Beauty",
        "Brand": "GlowUp",
        "Quantity Sold": 1,
        "Unit Price": 3748.29,
        "Total Amount": 4314.57,
        "Discount Applied": 187.41,
        "Shipping Charges": 79,
        "Net Revenue": 3272.24,
        "Currency": "INR",
        "Payment Method": "Net Banking",
        "Fulfilled By": "Warehouse A",
        "Delivery Status": "Delivered",
        "Delivery Date": "2024-10-14",
        "Warehouse Location": "Bengaluru",
        "Shipping Partner": "BlueDart",
        "Customer Region": "Central",
        "Stock Level": 26,
        "Profit Margin": 0.10,
        "Sales Channel": "Marketplace",
    },
    {
        "Order ID": "ORD00002",
        "Order Date": "2024-06-09",
        "Customer ID": "CUST2782",
        "Customer Name": "Customer 490",
        "Product ID / SKU": "SKU18627",
        "Product Name": "Almonds 500g",
        "Category": "Grocery",
        "Brand": "GoodGrain",
        "Quantity Sold": 5,
        "Unit Price": 2329.87,
        "Total Amount": 13746.23,
        "Discount Applied": 0.00,
        "Shipping Charges": 0,
        "Net Revenue": 8500.75,
        "Currency": "INR",
        "Payment Method": "Net Banking",
        "Fulfilled By": "3PL Partner",
        "Delivery Status": "In-Transit",
        "Delivery Date": "2024-06-13",
        "Warehouse Location": "Delhi",
        "Shipping Partner": "Delhivery",
        "Customer Region": "North",
        "Stock Level": 216,
        "Profit Margin": 0.07,
        "Sales Channel": "Website",
    },
    {
        "Order ID": "ORD00003",
        "Order Date": "2024-12-12",
        "Customer ID": "CUST8641",
        "Customer Name": "Customer 188",
        "Product ID / SKU": "SKU30053",
        "Product Name": "LED Lamp",
        "Category": "Home",
        "Brand": "CasaPro",
        "Quantity Sold": 5,
        "Unit Price": 4202.57,
        "Total Amount": 24795.16,
        "Discount Applied": 0.00,
        "Shipping Charges": 0,
        "Net Revenue": 19166.52,
        "Currency": "INR",
        "Payment Method": "Credit Card",
        "Fulfilled By": "Warehouse A",
        "Delivery Status": "In-Transit",
        "Delivery Date": "2024-12-14",
        "Warehouse Location": "Delhi",
        "Shipping Partner": "Ecom Express",
        "Customer Region": "East",
        "Stock Level": 250,
        "Profit Margin": 0.17,
        "Sales Channel": "Marketplace",
    },
    {
        "Order ID": "ORD00004",
        "Order Date": "2024-10-20",
        "Customer ID": "CUST3451",
        "Customer Name": "Customer 489",
        "Product ID / SKU": "SKU20565",
        "Product Name": "Pasta Pack",
        "Category": "Grocery",
        "Brand": "GoodGrain",
        "Quantity Sold": 2,
        "Unit Price": 4411.61,
        "Total Amount": 9608.08,
        "Discount Applied": 882.32,
        "Shipping Charges": 79,
        "Net Revenue": 6648.08,
        "Currency": "INR",
        "Payment Method": "Net Banking",
        "Fulfilled By": "3PL Partner",
        "Delivery Status": "Delivered",
        "Delivery Date": "2024-10-26",
        "Warehouse Location": "Hyderabad",
        "Shipping Partner": "BlueDart",
        "Customer Region": "Central",
        "Stock Level": 226,
        "Profit Margin": 0.16,
        "Sales Channel": "Retail Store",
    },
    {
        "Order ID": "ORD00005",
        "Order Date": "2024-09-09",
        "Customer ID": "CUST6613",
        "Customer Name": "Customer 333",
        "Product ID / SKU": "SKU41522",
        "Product Name": "Ceramic Vase",
        "Category": "Home",
        "Brand": "Decora",
        "Quantity Sold": 3,
        "Unit Price": 1233.16,
        "Total Amount": 4199.42,
        "Discount Applied": 184.97,
        "Shipping Charges": 19,
        "Net Revenue": 3341.04,
        "Currency": "INR",
        "Payment Method": "Net Banking",
        "Fulfilled By": "3PL Partner",
        "Delivery Status": "Shipped",
        "Delivery Date": "2024-09-12",
        "Warehouse Location": "Hyderabad",
        "Shipping Partner": "BlueDart",
        "Customer Region": "North",
        "Stock Level": 60,
        "Profit Margin": 0.12,
        "Sales Channel": "Mobile App",
    },
])

# Save to CSV (UTF-8, no index)
df.to_csv('sales_output.csv', index=False, encoding='utf-8')

# Save to Excel (requires openpyxl), sheet named 'Sales'
df.to_excel('sales_output.xlsx', index=False, sheet_name='Sales')

# Confirmation prints
print('Saved sales_output.csv and sales_output.xlsx')

